startingSlotVelocityMS:
  min: 16
  max: 85
finalTickInterval:
  min: 850
  max: 1250
frictionCoeffecient: 1.3
slots:
  - name: "game type"
    options:
      - "augmented reality"
      - "deckbuilding"
      - "dexterity"
      - "children's"
      - "roleplaying"
      - "puzzle"
      - "party"
      - "roll and move"
      - "worker placement"
      - "cooperative"
      - "area control"
      - "social deception"
      - "legacy"
      - "combat"
  - name: "theme"
    options:
      - "agriculture"
      - "alchemy"
      - "reproduction"
      - "commerce"
      - "conflict resolution"
      - "cooking"
      - "cosmic horror"
      - "disease control"
      - "evolution"
      - "exploration"
      - "fantasy"
      - "financial planning"
      - "food chain"
      - "geometric"
      - "hegemony"
      - "hoarding"
      - "invention"
      - "life-cycle"
      - "manifest destiny"
      - "martial arts"
      - "disarmament"
      - "relationships"
      - "pirates"
      - "prehistory"
      - "racing"
      - "river fjording"
      - "steampunk"
      - "trains"
      - "warfare"
  - name: "key mechanic"
    options:
      - "action points"
      - "area-impulse"
      - "asymettry"
      - "auctions"
      - "battle royale"
      - "betting"
      - "blackbox"
      - "card drafting"
      - "collaboration"
      - "drafting"
      - "grid movement"
      - "if you die it the game you die in real life"
      - "map exploration"
      - "memory"
      - "multiple victory conditions"
      - "partnership"
      - "pattern building"
      - "perfect knowledge"
      - "permadeath"
      - "rondel"
      - "route building"
      - "rule changes"
      - "see-through cards"
      - "set collection"
      - "shared resources"
      - "storytelling"
      - "synergy"
      - "tile placement"
      - "time limit"
      - "trading"
